### PR TITLE
AACT-417: Do not crash on show page if load event doesn't have a verifier

### PR DESCRIPTION
**Pull request by Javier-Jimenez-18**
- Fixed bug so that the Verifier show and index page does not crash if a Load Event does not have a Verifier. 
- Created Verifiers requests tests Spec file. 
- Updated factories Spec file to be able to run requests tests.

Screen Shot 2022-10-05 at 10 43 24 AM
Screen Shot 2022-10-05 at 10 43 46 AM

Verifiers controller spec test:

Screen Shot 2022-10-05 at 10 40 16 AM

Verifiers requests spec test:

Screen Shot 2022-10-05 at 10 42 07 AM

### CODE REVIEW

**Comment by ievgend2** [comment]
Looks good, I did not get any errors during local test.
I can suggest to change order to descending, so we will don't need to scroll all the way to the bottom of the page to see the most recent run. 
Also, we can add a couple of zero's before the number of run, so it will look more professional:
example 0000287 instead of 287

**Review by ievgend2 — APPROVED** [review]

**Comment by ievgend2** [comment]
Why do we closed this PR instead of merging?

**Comment by Javier-Jimenez-18** [comment]
Renamed branch name to the following:

https://github.com/ctti-clinicaltrials/aact-admin/pull/236

**Comment by Javier-Jimenez-18** [comment]
It was closed and then re-opened as PR#236.

**Pull request closed without merging**
