### PR TITLE
AACT-434: Created table saved_queries

### PR DESCRIPTION
**Pull request by ievgend2**

### CODE REVIEW

**Review by Javier-Jimenez-18 — APPROVED** [review]
Looks good.

**Review by kholtzman5610 — APPROVED** [review]
Looks good.

**Review by micronix — APPROVED** [review]
looks good

**Comment by Javier-Jimenez-18** [comment]
This ticket (AACT-434, PR# 231) was revised and modified in ticket AACT-434: Create the database tables for the saved queries, PR# 243:

https://github.com/ctti-clinicaltrials/aact-admin/pull/243

**Pull request merged**
