### PR TITLE
Feat/AACT-362 Organize environment  variables in README.md

### PR DESCRIPTION
**Pull request by Javier-Jimenez-18**
Updated the environment variables in README.md file. Organized these variables in a table that shows the name and value, along with an explanation of each. Updated the Getting Started section:

Screen Shot 2022-03-28 at 6 13 06 PM

### CODE REVIEW

**Comment by Javier-Jimenez-18** [comment]
Added "Database Explanation" section including "AACT Database Visualization" png to README.md file:
Screen Shot 2022-03-31 at 2 55 31 PM

**Review by micronix — CHANGES_REQUESTED** [review]
remove the image so that it is not stored in aact admin

**Review by micronix — APPROVED** [review]
Looks good

**Review by micronix — COMMENTED** [review]
Looks good

**Pull request merged**
