### PR TITLE
Removed the double error but still need to change font weight

### PR DESCRIPTION
**Pull request by ievgend2**
See Jira for comments.

### CODE REVIEW

**Review by Javier-Jimenez-18 — COMMENTED** [review]
Looks good.

**Review by Javier-Jimenez-18 — COMMENTED** [review]
Looks ok to me. But maybe attach some screenshots to see the changes?

Also need to resolve branch conflicts.

**Comment by Javier-Jimenez-18** [comment]
I just saw that you included the screenshots in the Jira AACT-408 ticket.

**Review by micronix — APPROVED** [review]
Looks good

**Pull request merged**
