### PR TITLE
AACT-401: Add edit & update & show actions to the data_definitions controller

### PR DESCRIPTION
**Pull request by Javier-Jimenez-18**
Added the edit and update actions to the DataDefinitions controller. Added a link to the edit action in the index view page. Created the form and view page for the edit action. Added the edit and update actions Rspec controller tests.

Screen Shot 2022-07-15 at 5 23 03 PM
Screen Shot 2022-07-16 at 3 09 48 PM
Screen Shot 2022-07-16 at 3 10 03 PM
Screen Shot 2022-07-16 at 3 12 01 PM
Screen Shot 2022-07-16 at 3 12 45 PM
Screen Shot 2022-07-16 at 3 13 48 PM
Screen Shot 2022-07-16 at 3 05 57 PM

### CODE REVIEW

**Comment by micronix** [comment]
We decided to add a show page to each data definition, the show page will show all the data in the row and have an edit and delete button.

In the index view we are combining the table and column name into one field with a dot separating the two for example if the table is baseline_measures and the column is id the value would be `baseline_measures.id`

**Comment by ievgend2** [comment]
it is looks great on my side, i dont know why there is Table cut on Javier side.
image

**Comment by Javier-Jimenez-18** [comment]
Added show action and view page for each Data Definition. Moved edit button from index page to the show page. Combined the table and column name into one field in the index page. Added a link in the db_section column to show each Data Definition.  Added the show action Data Definition controller Rspec test.

Screen Shot 2022-07-21 at 1 52 07 PM
Screen Shot 2022-07-21 at 1 55 53 PM
Screen Shot 2022-07-21 at 1 57 09 PM
Screen Shot 2022-07-21 at 1 57 23 PM
Screen Shot 2022-07-21 at 2 09 11 PM

**Comment by Javier-Jimenez-18** [comment]
Modified Data Definitions index page to make table_name and column_name a link, instead of db_section, to the show page. Updated the first and second column of the table in the index page, and removed the "and" and replaced it with a "."

Screen Shot 2022-07-22 at 10 14 22 AM

**Review by micronix — APPROVED** [review]
looks good

**Pull request merged**
