### PR TITLE
As an admin I want to see a list of verifier results.

### PR DESCRIPTION
**Pull request by kholtzman5610**
- Added the verifier option to admin menu app/views/includes/_main_header.html.erb
- Added testing (all passing)
- Removed `:is admin` from Verifiers Controller 

### Index
verifiers_index

### Show View with Verifier in admin menu
verifiers_show

### CODE REVIEW

**Review by Javier-Jimenez-18 — CHANGES_REQUESTED** [review]
Good job. Just a few suggestions:

- Please add screenshot of the Verifiers index page so we can see how it looks. 
- For the Verifier show page, you might want to show the Differences (should it be called Verifier?) table last so that we can see the "Last Run", "Created at", and "Updated at" data first (when the table gets too long, you will have to scroll down many times to get to the end).
- You should add a get #show controller test.
- Ask @micronix if you need to do Request specs of the Verifiers.

**Review by micronix — CHANGES_REQUESTED** [review]
There are some issues with tests and some styling changes that are required.

**Comment by Javier-Jimenez-18** [comment]
Hey Kassi, 

The coding looks good. But, can you please attach some screenshots to see how the fixes look? 

Great job!

**Review by micronix — APPROVED** [review]
Looks good

**Pull request merged**
